// Recetas e ingredientes por defecto — Il Popolo (IDs de menu.ts).

type StockIngrediente = {
  nombre: string;
  stockGramos: number;
  minimoGramos: number;
  unidad: "g" | "ud" | "lata";
};

/** Base pizza estándar (hostelería). */
const PZ = { masa_pizza: 250, salsa_tomate: 80, mozzarella: 100, oregano: 2 } as const;

/** Base pinsa (masa algo mayor). */
const PI = { masa_pinsa: 280, salsa_tomate: 80, mozzarella: 100, oregano: 2 } as const;

export const RECETAS_IL_POPOLO: Record<string, Record<string, number>> = {
  // —— PIZZAS ——
  pz01: { ...PZ },
  pz02: { ...PZ, jamon_york: 50 },
  pz03: { ...PZ, atun: 1, cebolla: 30, pimiento: 40, olivas: 15 },
  pz04: { ...PZ, cebolla: 35, jamon_york: 45, beicon: 40, huevo: 1 },
  pz05: {
    ...PZ,
    masa_pizza: 280,
    jamon_york: 45,
    huevo: 1,
    queso_cabra: 35,
    rucula: 15,
    jamon_serrano: 30,
    parmesano: 15,
  },
  pz06: {
    ...PZ,
    champiñon: 40,
    alcachofas: 35,
    jamon_york: 40,
    atun: 0.5,
    anchoas: 15,
    olivas: 15,
  },
  pz07: { ...PZ, jamon_york: 45, champiñon: 45, cebolla: 30 },
  pz08: { ...PZ, salami: 45, anchoas: 20, olivas: 15 },
  pz09: { ...PZ, queso_cabra: 35, gorgonzola: 30, parmesano: 25 },
  pz10: { ...PZ, atun: 0.5, cebolla: 30, champiñon: 40, olivas: 15 },
  pz11: { ...PZ, jamon_york: 40, champiñon: 35, salami: 35, guindilla: 3 },
  pz12: {
    masa_pizza: 250,
    salsa_tomate: 80,
    oregano: 2,
    mozzarella_vegana: 100,
    pollo_vegano: 70,
    salsa_barbacoa: 40,
    cebolla: 30,
  },

  // —— PINSAS ——
  pi01: { ...PI, berenjena: 60, parmesano: 20, albahaca: 2 },
  pi02: { ...PI, jamon_serrano: 35, gorgonzola: 35, pera: 40 },
  pi03: { ...PI, pepperoni: 40, pollo: 60, champiñon: 40, guindilla: 3 },
  pi04: { ...PI, salmon: 70, huevas: 15 },
  pi05: {
    ...PI,
    tomate_cherry: 40,
    berenjena: 50,
    pimiento_asado: 45,
    rucula: 20,
    burrata: 80,
  },

  // —— PASTAS FRESCAS ——
  pf01: {
    rigatoni: 180,
    salsa_bolognesa: 120,
    carne_picada: 80,
    cebolla: 25,
    parmesano: 15,
  },
  pf02: {
    espagueti: 180,
    guanciale: 50,
    parmesano: 30,
    huevo: 1,
    pimienta: 2,
  },
  pf03: {
    espagueti: 180,
    guanciale: 60,
    parmesano: 30,
    huevo: 1,
    pimienta: 2,
  },
  pf04: {
    papardelle: 180,
    secreto: 90,
    salsa_nueces: 25,
    champiñon: 50,
    nata: 30,
  },
  pf05: {
    papardelle: 180,
    gambas: 80,
    mejillones: 60,
    salsa_tomate: 50,
    ajo: 5,
    guindilla: 2,
    albahaca: 2,
  },

  // —— PASTAS RELLENAS ——
  pr01: {
    pasta_rellena: 200,
    carne_picada: 50,
    salsa_trufa: 40,
    champiñon: 35,
    nata: 25,
  },
  pr02: {
    pasta_rellena: 200,
    requeson: 50,
    espinacas: 40,
    gorgonzola: 35,
    nueces: 15,
    nata: 30,
  },
  pr03: {
    pasta_rellena: 200,
    salmon: 60,
    gambas: 50,
    salsa_tomate: 40,
    tomate_cherry: 30,
    cebolla: 20,
    rucula: 10,
  },
  pr04: {
    pasta_rellena: 200,
    requeson: 45,
    nueces: 20,
    pesto_almendras: 25,
    tomate_seco: 20,
    parmesano: 15,
  },
  pr05: {
    pasta_rellena: 180,
    provolone: 70,
    cebolla: 40,
    foie: 25,
    aceite_trufa: 5,
  },
  pr06: {
    pasta_rellena: 220,
    carne_picada: 70,
    salsa_bolognesa: 50,
    champiñon: 40,
  },

  // —— LASAGNAS ——
  la01: {
    laminas_lasana: 120,
    salsa_bolognesa: 150,
    bechamel: 80,
    mozzarella: 60,
    parmesano: 20,
  },
  la02: {
    laminas_lasana: 120,
    bechamel: 90,
    mozzarella: 60,
    espinacas: 50,
    champiñon: 40,
    parmesano: 20,
    salsa_tomate: 40,
  },

  // —— ENTRANTES ——
  en01: { pan_ajo: 120, mantequilla_ajo: 25, perejil: 2 },
  en02: { berenjena: 150, harina: 20, aceite_oliva: 15, miel: 25 },
  en03: { patata: 200, jamon_serrano: 40, mozzarella: 50, nata: 30 },
  en04: { provolone: 80, cebolla: 50, foie: 30, aceite_oliva: 5 },
  en05: { harina: 40, huevo: 1, leche: 40, champiñon: 60, gorgonzola: 35, nata: 40 },
  en06: { provolone: 90, verduras_asadas: 80, aceite_trufa: 5 },
  en07: {
    boletus: 120,
    guanciale: 40,
    parmesano: 25,
    huevo: 1,
    pimienta: 2,
    nata: 20,
  },
  en08: { croqueta_masa: 160, jamon_york: 50, bechamel: 40, huevo: 0.5, mayonesa: 25 },
  en09: { croqueta_masa: 160, boletus: 60, bechamel: 40, huevo: 0.5, mayonesa: 25, aceite_trufa: 3 },
  en10: {
    burrata: 100,
    harina: 25,
    huevo: 0.5,
    tomate_cherry: 40,
    pistachos: 15,
    aceite_oliva: 8,
  },

  // —— ENSALADAS ——
  es01: {
    lechuga: 80,
    tomate: 50,
    zanahoria: 25,
    esparrago: 30,
    huevo: 1,
    atun: 0.5,
    jamon_york: 30,
    mozzarella: 25,
    salsa_rosa: 30,
  },
  es02: {
    lechuga: 90,
    pollo: 80,
    parmesano: 20,
    tomate_cherry: 35,
    salsa_cesar: 30,
    crouton: 15,
  },
  es03: {
    lechuga: 85,
    tomate_cherry: 40,
    queso_cabra: 45,
    vinagreta_mango: 25,
    nueces: 15,
  },
  es04: {
    brotes: 30,
    tomate_cherry: 45,
    burrata: 90,
    pera: 40,
    jamon_serrano: 35,
    tartufata: 15,
  },

  // —— ENSALADILLAS (ración ~150 g) ——
  eq01: { patata_cocida: 100, zanahoria: 20, guisantes: 15, huevo: 0.5, mayonesa: 35 },
  eq02: { patata_cocida: 90, surimi: 25, mayonesa: 35, huevo: 0.3 },
  eq03: { patata_cocida: 85, gambas: 25, mejillones: 20, mayonesa: 35 },
  eq04: { patata_cocida: 90, surimi: 20, gambas: 25, mayonesa: 35 },
  eq05: { patata_cocida: 95, alcachofas: 40, mayonesa: 30, huevo: 0.3 },

  // —— PAN ÁRABO ——
  pa01: {
    pan_arabe: 180,
    mozzarella: 50,
    jamon_serrano: 45,
    tomate: 40,
    lechuga: 25,
    aceite_oliva: 8,
  },
  pa02: {
    pan_arabe: 180,
    mayonesa: 25,
    pollo: 70,
    tomate: 40,
    lechuga: 25,
  },
  pa03: {
    pan_arabe: 180,
    mayonesa: 25,
    lomo: 75,
    pimiento: 35,
    lechuga: 25,
    tomate: 35,
  },
  pa04: {
    pan_arabe: 180,
    mayonesa: 25,
    lomo: 65,
    beicon: 35,
    tomate: 35,
    lechuga: 25,
  },
  pa05: {
    pan_arabe: 180,
    mayonesa: 25,
    atun: 0.5,
    huevo: 1,
    cebolla: 25,
    tomate: 35,
    lechuga: 25,
  },
  pa06: {
    pan_arabe: 180,
    salmon: 65,
    aguacate: 40,
    tomate: 35,
    lechuga: 25,
    mozzarella: 30,
  },

  // —— POSTRES ——
  po01: { chocolate: 45, chocolate_blanco: 25, chocolate_leche: 25, nata: 20 },
  po02: { queso_tarta: 80, base_galleta: 25, nata: 15 },
  po03: { queso_tarta: 90, base_galleta: 25, huevo: 0.5, nata: 20 },
  po04: { mascarpone: 60, cafe: 30, cacao: 8, bizcocho: 25, huevo: 0.5 },
  po05: { leche: 120, huevo: 0.5, azucar: 25, vainilla: 2 },
  po06: { torta_chocolate: 70, helado: 50, nocilla: 20 },
};

/** Stock inicial de ingredientes Il Popolo (unidad en gramos salvo ud/lata). */
export function crearStockIlPopolo(): Map<string, StockIngrediente> {
  return new Map<string, StockIngrediente>([
    ["masa_pizza", { nombre: "Masa de pizza", stockGramos: 50000, minimoGramos: 15000, unidad: "g" }],
    ["masa_pinsa", { nombre: "Masa de pinsa", stockGramos: 20000, minimoGramos: 8000, unidad: "g" }],
    ["salsa_tomate", { nombre: "Salsa de tomate", stockGramos: 3000, minimoGramos: 1500, unidad: "g" }],
    ["mozzarella", { nombre: "Mozzarella", stockGramos: 3000, minimoGramos: 2000, unidad: "g" }],
    ["mozzarella_vegana", { nombre: "Mozzarella vegana", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["oregano", { nombre: "Orégano", stockGramos: 500, minimoGramos: 100, unidad: "g" }],
    ["jamon_york", { nombre: "Jamón york", stockGramos: 1500, minimoGramos: 800, unidad: "g" }],
    ["jamon_serrano", { nombre: "Jamón serrano", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["beicon", { nombre: "Beicon", stockGramos: 500, minimoGramos: 400, unidad: "g" }],
    ["atun", { nombre: "Atún", stockGramos: 24, minimoGramos: 6, unidad: "lata" }],
    ["cebolla", { nombre: "Cebolla", stockGramos: 1000, minimoGramos: 300, unidad: "g" }],
    ["pimiento", { nombre: "Pimiento", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["pimiento_asado", { nombre: "Pimiento asado", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["olivas", { nombre: "Olivas", stockGramos: 600, minimoGramos: 200, unidad: "g" }],
    ["huevo", { nombre: "Huevo", stockGramos: 36, minimoGramos: 12, unidad: "ud" }],
    ["queso_cabra", { nombre: "Queso de cabra", stockGramos: 400, minimoGramos: 200, unidad: "g" }],
    ["rucula", { nombre: "Rúcula", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["parmesano", { nombre: "Parmesano", stockGramos: 300, minimoGramos: 150, unidad: "g" }],
    ["champiñon", { nombre: "Champiñón", stockGramos: 800, minimoGramos: 400, unidad: "g" }],
    ["alcachofas", { nombre: "Alcachofas", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["salami", { nombre: "Salami", stockGramos: 400, minimoGramos: 200, unidad: "g" }],
    ["anchoas", { nombre: "Anchoas", stockGramos: 200, minimoGramos: 100, unidad: "g" }],
    ["gorgonzola", { nombre: "Gorgonzola", stockGramos: 350, minimoGramos: 150, unidad: "g" }],
    ["guindilla", { nombre: "Guindilla", stockGramos: 100, minimoGramos: 30, unidad: "g" }],
    ["pollo_vegano", { nombre: "Pollo vegano", stockGramos: 600, minimoGramos: 200, unidad: "g" }],
    ["salsa_barbacoa", { nombre: "Salsa barbacoa", stockGramos: 1000, minimoGramos: 400, unidad: "g" }],
    ["berenjena", { nombre: "Berenjena", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["albahaca", { nombre: "Albahaca", stockGramos: 80, minimoGramos: 30, unidad: "g" }],
    ["pera", { nombre: "Pera", stockGramos: 500, minimoGramos: 150, unidad: "g" }],
    ["pepperoni", { nombre: "Pepperoni", stockGramos: 500, minimoGramos: 300, unidad: "g" }],
    ["pollo", { nombre: "Pollo", stockGramos: 700, minimoGramos: 300, unidad: "g" }],
    ["salmon", { nombre: "Salmón", stockGramos: 380, minimoGramos: 300, unidad: "g" }],
    ["huevas", { nombre: "Huevas", stockGramos: 150, minimoGramos: 50, unidad: "g" }],
    ["tomate_cherry", { nombre: "Tomate cherry", stockGramos: 600, minimoGramos: 200, unidad: "g" }],
    ["burrata", { nombre: "Burrata", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["rigatoni", { nombre: "Rigatoni", stockGramos: 5000, minimoGramos: 2000, unidad: "g" }],
    ["espagueti", { nombre: "Espagueti", stockGramos: 5000, minimoGramos: 2000, unidad: "g" }],
    ["papardelle", { nombre: "Papardelle", stockGramos: 3000, minimoGramos: 1000, unidad: "g" }],
    ["salsa_bolognesa", { nombre: "Salsa boloñesa", stockGramos: 2000, minimoGramos: 800, unidad: "g" }],
    ["carne_picada", { nombre: "Carne picada", stockGramos: 1500, minimoGramos: 600, unidad: "g" }],
    ["guanciale", { nombre: "Guanciale", stockGramos: 600, minimoGramos: 250, unidad: "g" }],
    ["pimienta", { nombre: "Pimienta", stockGramos: 200, minimoGramos: 50, unidad: "g" }],
    ["secreto", { nombre: "Secreto ibérico", stockGramos: 600, minimoGramos: 250, unidad: "g" }],
    ["salsa_nueces", { nombre: "Salsa de nueces", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["nata", { nombre: "Nata", stockGramos: 1500, minimoGramos: 500, unidad: "g" }],
    ["gambas", { nombre: "Gambas", stockGramos: 350, minimoGramos: 400, unidad: "g" }],
    ["mejillones", { nombre: "Mejillones", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["ajo", { nombre: "Ajo", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["pasta_rellena", { nombre: "Pasta rellena (ravioli/pansotti)", stockGramos: 4000, minimoGramos: 1500, unidad: "g" }],
    ["salsa_trufa", { nombre: "Salsa de trufa", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["requeson", { nombre: "Requesón", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["espinacas", { nombre: "Espinacas", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["nueces", { nombre: "Nueces", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["pesto_almendras", { nombre: "Pesto de almendras", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    ["tomate_seco", { nombre: "Tomate seco", stockGramos: 250, minimoGramos: 80, unidad: "g" }],
    ["provolone", { nombre: "Provolone", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["foie", { nombre: "Foie", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["aceite_trufa", { nombre: "Aceite de trufa", stockGramos: 150, minimoGramos: 50, unidad: "g" }],
    ["laminas_lasana", { nombre: "Láminas de lasaña", stockGramos: 3000, minimoGramos: 1000, unidad: "g" }],
    ["bechamel", { nombre: "Bechamel", stockGramos: 1500, minimoGramos: 600, unidad: "g" }],
    ["pan_ajo", { nombre: "Pan de ajo (base)", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["mantequilla_ajo", { nombre: "Mantequilla de ajo", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    ["perejil", { nombre: "Perejil", stockGramos: 80, minimoGramos: 30, unidad: "g" }],
    ["harina", { nombre: "Harina", stockGramos: 5000, minimoGramos: 2000, unidad: "g" }],
    ["miel", { nombre: "Miel", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    ["aceite_oliva", { nombre: "Aceite de oliva", stockGramos: 2000, minimoGramos: 500, unidad: "g" }],
    ["patata", { nombre: "Patata", stockGramos: 3000, minimoGramos: 1000, unidad: "g" }],
    ["leche", { nombre: "Leche", stockGramos: 3000, minimoGramos: 1000, unidad: "g" }],
    ["verduras_asadas", { nombre: "Verduras asadas", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["boletus", { nombre: "Boletus", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["croqueta_masa", { nombre: "Masa de croqueta", stockGramos: 1500, minimoGramos: 500, unidad: "g" }],
    ["mayonesa", { nombre: "Mayonesa", stockGramos: 1200, minimoGramos: 400, unidad: "g" }],
    ["pistachos", { nombre: "Pistachos", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["lechuga", { nombre: "Lechuga", stockGramos: 600, minimoGramos: 200, unidad: "g" }],
    ["tomate", { nombre: "Tomate", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["zanahoria", { nombre: "Zanahoria", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["esparrago", { nombre: "Espárrago", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["salsa_rosa", { nombre: "Salsa rosa", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["salsa_cesar", { nombre: "Salsa césar", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["crouton", { nombre: "Croutons", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    ["vinagreta_mango", { nombre: "Vinagreta de mango", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    ["brotes", { nombre: "Brotes", stockGramos: 150, minimoGramos: 50, unidad: "g" }],
    ["tartufata", { nombre: "Tartufata", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["patata_cocida", { nombre: "Patata cocida", stockGramos: 2000, minimoGramos: 800, unidad: "g" }],
    ["guisantes", { nombre: "Guisantes", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["surimi", { nombre: "Surimi", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["pan_arabe", { nombre: "Pan árabo", stockGramos: 1200, minimoGramos: 400, unidad: "g" }],
    ["lomo", { nombre: "Lomo de cerdo", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["aguacate", { nombre: "Aguacate", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["chocolate", { nombre: "Chocolate negro", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["chocolate_blanco", { nombre: "Chocolate blanco", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    ["chocolate_leche", { nombre: "Chocolate con leche", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    ["queso_tarta", { nombre: "Queso para tarta", stockGramos: 600, minimoGramos: 250, unidad: "g" }],
    ["base_galleta", { nombre: "Base de galleta", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["mascarpone", { nombre: "Mascarpone", stockGramos: 500, minimoGramos: 200, unidad: "g" }],
    ["cafe", { nombre: "Café (espresso)", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["cacao", { nombre: "Cacao", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
    ["bizcocho", { nombre: "Bizcocho", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["azucar", { nombre: "Azúcar", stockGramos: 2000, minimoGramos: 500, unidad: "g" }],
    ["vainilla", { nombre: "Vainilla", stockGramos: 50, minimoGramos: 15, unidad: "g" }],
    ["torta_chocolate", { nombre: "Torta de chocolate", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["helado", { nombre: "Helado", stockGramos: 800, minimoGramos: 300, unidad: "g" }],
    ["nocilla", { nombre: "Nocilla", stockGramos: 300, minimoGramos: 100, unidad: "g" }],
    // Alias / legado panel
    ["salsa_nata", { nombre: "Salsa de nata", stockGramos: 600, minimoGramos: 300, unidad: "g" }],
    ["roquefort", { nombre: "Roquefort", stockGramos: 250, minimoGramos: 100, unidad: "g" }],
    ["carne_hamburguesa", { nombre: "Carne picada (legado)", stockGramos: 800, minimoGramos: 400, unidad: "g" }],
    ["pollo_empanado", { nombre: "Pollo empanado", stockGramos: 600, minimoGramos: 300, unidad: "g" }],
    ["piña", { nombre: "Piña", stockGramos: 400, minimoGramos: 150, unidad: "g" }],
    ["pasas", { nombre: "Pasas", stockGramos: 200, minimoGramos: 80, unidad: "g" }],
  ]);
}
